# Basic Configuration  
name: Reverie  
author: Your Name  
description: An elegant Jekyll theme  
avatar: /images/reverie.png  
  
# Social Links in Footer  
footer-links:  
  dribbble:   
  email: your-email@example.com  
  facebook:   
  flickr:   
  github: your-username  
  instagram:   
  linkedin:   
  pinterest:   
  rss: rss  
  twitter: your_twitter_handle  
  stackoverflow:   
  youtube: # channel/<your_long_string> or user/<user-name>  
  googleplus: # anything in your profile username that comes after plus.google.com/  
  playconsole:   
  mastodon: # <your-mastodon-instance>/@<your-user-name> eg. fosstodon.org/@username  
  
# Disqus for Comments  
disqus: your-disqus-shortname  
  
# Google Analytics  
google_analytics: UA-XXXXXXXX-X  
# For newer "GA4" analytics, use the following instead of the "UA" entry above  
# google_analytics_ga4: G-GABC1DEFG  
  
# Website URL  
url: https://yourusername.github.io  
enforce_ssl: https://yourusername.github.io  
  
# Base URL  
baseurl: ""  
  
# Kramdown and Rouge Configuration for Markdown and Syntax Highlighting  
kramdown:  
  input: GFM  
  syntax_highlighter: rouge  
  syntax_highlighter_opts:  
    css_class: 'highlight'  
  
# Sass Configuration  
sass:  
  style: expanded  
  
# Plugins  
plugins:  
  - jekyll-sitemap  
  - jekyll-feed  
  - jekyll-seo-tag  
  - jekyll-paginate  
  
# Pagination  
paginate: 6  
paginate_path: /page:num/  
  
# Include Pages Directory  
include: ['_pages']  
  
# Exclude Files from Production  
exclude:  
  - Gemfile  
  - Gemfile.lock  
  - LICENSE  
  - README.md  
  - CNAME  
